# Generated by Django 6.0.2 on 2026-04-22 07:17

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=4)),
                ("image", models.ImageField(upload_to="project_images/")),
                ("client", models.CharField(max_length=100)),
                ("service", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("about_desc", models.TextField()),
                ("overview_desc", models.TextField()),
                ("site_url", models.URLField()),
                ("image_1", models.ImageField(upload_to="project_images/")),
                ("image_2", models.ImageField(upload_to="project_images/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectAboutList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                (
                    "project",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_lists",
                        to="core.project",
                    ),
                ),
            ],
        ),
    ]
